version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_for_go_anything
    networks:
      - go-anything-network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: adminMysql
      MYSQL_DATABASE: go-anything
      MYSQL_USER: root
    ports:
      - 3306:3306
  go-anything:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8888
    depends_on:
      - mysql
    links:
      - mysql:mysql
    networks:
      - go-anything-network
networks:
  go-anything-network:
    driver: bridge