version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_for_go_anything
    expose:
      - 3307
      - 3306
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: adminMysql
      MYSQL_DATABASE: go-anything
      MYSQL_USER: root
    networks:
      - go-anything-network
    volumes:
      - data:/var/lib/mysql
networks:
  go-anything-network:
    driver: bridge
volumes:
  data: {}
  dir: {}