apiVersion: v1
kind: Pod
metadata:
  name: k8s-example-pod
  namespace: k8s-example
  labels:
    app: k8s-example-pod
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
