version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
    container_name: redis_for_go_anything
    command: redis-server --appendonly yes --requirepass "adminRedis"
  mysql:
    image: mysql:latest
    container_name: mysql_for_go_anything
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: adminMysql
      MYSQL_DATABASE: go-anything
      MYSQL_USER: root
    ports:
      - 3307:3306
      - 33060:33060
    expose:
      - 3306
      - 33060
  kafka:
    image: index.docker.io/wurstmeister/kafka:latest
    container_name: kafka_for_go_anything
    ports:
      - 9092:9092
    environment:
      KAFKA_OFFSETS_TOPIC_REPLIATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "go-anything:20:1:compact"
    depends_on:
      - zookeeper
  zookeeper:
    image: index.docker.io/wurstmeister/zookeeper:latest
    container_name: zookeeper_for_go_anything
    ports:
      - 2181:2181
  go-anything:
    container_name: go-anything-project
    image: wuxiaoshen/go-anything:v0.9
    ports:
      - 8081:8888
    links:
      - mysql
      - redis
      - kafka
    depends_on:
      - zookeeper
    command: ["bash","-c", "go run /go/src/github.com/wuxiaoxiaoshen/go-anything/main.go"]
