version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis-1
    networks:
      - network-service
  mysql:
    image: mysql:latest
    container_name: mysql-1
    networks:
      - network-service
  postgres:
    image: postgres:latest
    container_name: postgres-1
    networks:
      - network-service
  go-anything:
    container_name: go-anything-1
    build:
    depends_on:
      - redis
      - mysql
      - postgres
    networks:
      - network-service

networks:
  network-service:
    driver: bridge
volumes:
  data: {}
