FROM golang:1.13.4-alpine3.10
MAINTAINER XieWei(1156143589@qq.com)
EXPOSE 8888 8081
WORKDIR /go/src/go-anything
VOLUME go/src/go-anything

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

COPY . .

RUN apt-get update && apt-get install -q -y vim nginx postgresql-client git openssh-client cron && apt-get clean;\
    go mod vendor;\
    go build -o main main.go;\
    echo Succeed!
CMD /go/src/main