version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis-1
    networks:
      - network-service
    ports:
      - 6379:6379
    command:  redis-server --appendonly yes
  mysql:
    image: mysql:latest
    container_name: mysql-1
    networks:
      - network-service
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD="admin123"
  postgres:
    image: postgres:latest
    container_name: postgres-1
    networks:
      - network-service
    ports:
      - 5432:5432
  go-anything:
    container_name: go-anything-1
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - 8081:8888
      - 8082:8888
    depends_on:
      - redis
      - mysql
      - postgres
    networks:
      - network-service
    command: ["bash","-c", "go run go/src/go-anything/main.go"]

networks:
  network-service:
    driver: bridge
volumes:
  data:
