version: "v1"
author: "XieWei"
weChat: "wu_xiaoshen"
service:
  mysql:
    port: "3306"
    db: go-anything
    user: root
    passwd: adminMysql
    host: mysql
  redis:
    port: "6379"
    auth: adminRedis
    host: redis
  kafka:
    broker: kafka:9092
    topic: go-anything
    consumerGroup: go-anything-consumer-group
  es:
    address: es:9200
    user: ""
    password: ""
  email:
    sender: "1156143589@qq.com"
    auth: "bWVuZ3d1MTliYW5nNTg1MjA="
    receivers:
      - "xiewei@tkzc31.onexmail.com"
dev:
  mysql:
    port: "3307"
    db: go-anything
    user: root
    passwd: adminMysql
    host: "127.0.0.1"
  redis:
    port: "6379"
    auth: adminRedis
    host: "127.0.0.1"
  kafka:
    broker: "127.0.0.1:9092"
    topic: go-anything
    consumerGroup: go-anything-consumer-group
  email:
    sender: "1156143589@qq.com"
    auth: "bWVuZ3d1MTliYW5nNTg1MjA="
    receivers:
      - "xiewei@tkzc31.onexmail.com"
  es:
    address: "127.0.0.1:9200"
    user: ""
    password: ""