apiVersion: apps/v1
kind: Deployment
metadata:
  name: xw-example-kafka-1-deployment
  labels:
    app: xw-example-kafka-1-deployment
  namespace: xw-example
spec:
  selector:
    matchLabels:
      app: xw-example-kafka-1
      role: kafka
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: xw-example-kafka-1
        role: kafka
    spec:
      containers:
        - name: xw-example-kafka-1
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          resources:
            limits:
              cpu: "1000m"
              memory: "2048Mi"
            requests:
              cpu: "500m"
              memory: "1024Mi"
          envFrom:
            - configMapRef:
                name: xw-example-configmap
          env:
            - name: KAFKA_PORT
              value: $(kafka.KAFKA_PORT)
            - name: KAFKA_LISTENERS
              value: $(kafka.KAFKA_LISTENERS)
            - name: KAFKA_ADVERTISED_PORT
              value: $(kafka.KAFKA_ADVERTISED_PORT)
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: $(kafka.KAFKA_ZOOKEEPER_CONNECT)
            - name: KAFKA_ADVERTISED_LISTENERS
              value: $(kafka.KAFKA_HOST_1)
            - name: KAFKA_BROKER_ID
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xw-example-kafka-2-deployment
  labels:
    app: xw-example-kafka-2-deployment
  namespace: xw-example
spec:
  selector:
    matchLabels:
      app: xw-example-kafka-2
      role: kafka
  template:
    metadata:
      labels:
        app: xw-example-kafka-2
        role: kafka
    spec:
      containers:
        - name: xw-example-kafka-2
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          resources:
            limits:
              cpu: "1000m"
              memory: "2048Mi"
            requests:
              cpu: "500m"
              memory: "1024Mi"
          envFrom:
            - configMapRef:
                name: xw-example-configmap
          env:
            - name: KAFKA_PORT
              value: $(kafka.KAFKA_PORT)
            - name: KAFKA_LISTENERS
              value: $(kafka.KAFKA_LISTENERS)
            - name: KAFKA_ADVERTISED_PORT
              value: $(kafka.KAFKA_ADVERTISED_PORT)
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: $(kafka.KAFKA_ZOOKEEPER_CONNECT)
            - name: KAFKA_ADVERTISED_LISTENERS
              value: $(kafka.KAFKA_HOST_2)
            - name: KAFKA_BROKER_ID
              value: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xw-example-kafka-3-deployment
  labels:
    app: xw-example-kafka-3-deployment
  namespace: xw-example
spec:
  selector:
    matchLabels:
      app: xw-example-kafka-3
      role: kafka
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: xw-example-kafka-3
        role: kafka
    spec:
      containers:
        - name: xw-example-kafka-3
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          resources:
            limits:
              cpu: "1000m"
              memory: "2048Mi"
            requests:
              cpu: "500m"
              memory: "1024Mi"
          envFrom:
            - configMapRef:
                name: xw-example-configmap
          env:
            - name: KAFKA_PORT
              value: $(kafka.KAFKA_PORT)
            - name: KAFKA_LISTENERS
              value: $(kafka.KAFKA_LISTENERS)
            - name: KAFKA_ADVERTISED_PORT
              value: $(kafka.KAFKA_ADVERTISED_PORT)
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: $(kafka.KAFKA_ZOOKEEPER_CONNECT)
            - name: KAFKA_ADVERTISED_LISTENERS
              value: $(kafka.KAFKA_HOST_3)
            - name: KAFKA-BROKER_ID
              value: "3"