apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: xw-example-kafka-podpreset
  labels:
    app: xw-example-kafka-podpreset
  namespace: xw-example
spec:
  selector:
    matchLabels:
      role: kafka
  envFrom:
    - configMapRef:
        name: xw-example-configmap
  env:
    - name: KAFKA_PORT
      value: $(kafka.KAFKA_PORT)
    - name: KAFKA_LISTENERS
      value: $(kafka.KAFKA_LISTENERS)
    - name: KAFKA_ADVERTISED_PORT
      value: $(kafka.KAFKA_ADVERTISED_PORT)
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: $(kafka.KAFKA_ZOOKEEPER_CONNECT)