apiVersion: apps/v1
kind: Deployment
metadata:
  name: xw-example-go-anything-deployment
  labels:
    app: xw-example-go-anything-deployment
  namespace: xw-example
spec:
  selector:
    matchLabels:
      app: xw-example-go-anything
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: xw-example-go-anything
        role: go-anything
    spec:
      containers:
        - name: go-anything
          imagePullPolicy: IfNotPresent
          image: swr.cn-north-1.myhuaweicloud.com/wuxiaoshen/go-anything:v0.23
          ports:
            - containerPort: 8888
#          volumeMounts:
#            - mountPath: "./"
#              name: go-anything-deployment-volume
          envFrom:
            - configMapRef:
                name: xw-example-configmap
          env:
            - name: MYSQL_HOST
              value: $(mysql.MYSQL_HOST)
            - name: MYSQL_PORT
              value: $(mysql.MYSQL_PORT)
            - name: REDIS_HOST
              value: $(redis.REDIS_HOST)
            - name: REDIS_PORT
              value: $(redis.REDIS_PORT)
            - name: KAFKA_BROKER_LIST
              value: $(kafka.KAFKA_BROKER_LIST)
            - name: METADATA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: METADATA_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RESOURCE_LIMITS_CPU
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
                  containerName: go-anything
            - name: RESOURCE_LIMITS_MEMORY
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  containerName: go-anything
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
          # PROBE
          # 存活
          livenessProbe:
            httpGet:
              path: /v1/api/status/health
              port: 8888
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 60
          # 准备就绪
          readinessProbe:
            httpGet:
              port: 8888
              path: /v1/api/tt/global
            periodSeconds: 120
            initialDelaySeconds: 30
            timeoutSeconds: 5
#      volumes:
#        - name: go-anything-deployment-volume
#          hostPath:
#            path: /xw/deployment
