apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: xw-example-go-anything-cronjob
  labels:
    app: xw-example-go-anything-cronjob
  namespace: xw-example
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: xw-example-go-anything-cronjob
              image: swr.cn-north-1.myhuaweicloud.com/wuxiaoshen/go-anything:v0.21
              command: ["bash", "-c", "/go/go-anything/go-anything", "email"]
          restartPolicy: OnFailure
  schedule: "*/1 * * * *"
