apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xw-example-go-anything-cronjob
  labels:
    app: xw-example-go-anything-cronjob
  namespace: xw-example
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: xw-example-go-anything-cronjob
              image: swr.cn-north-1.myhuaweicloud.com/wuxiaoshen/go-anything:v0.20
              args:
                - /bin/sh
                - -c
                - /go/src/github.com/wuxiaoxiaoshen/go-anything/main.go email
          restartPolicy: OnFailure
  schedule: "30 14 * * *"
