apiVersion: batch/v1
kind: Job
metadata:
  name: xw-example-db-job-2
  labels:
    app: xw-example-db-job-2
  namespace: xw-example
spec:
  template:
    spec:
      containers:
        - name: xw-example-db-job-2
          image: swr.cn-north-1.myhuaweicloud.com/wuxiaoshen/go-anything:v0.22
          imagePullPolicy: IfNotPresent
          command: ["bash","-c", "/go/go-anything/go-anything email"]
          envFrom:
            - configMapRef:
                name: xw-example-configmap
          env:
            - name: MYSQL_HOST
              value: $(mysql.MYSQL_HOST)
            - name: MYSQL_PORT
              value: $(mysql.MYSQL_PORT)
            - name: REDIS_HOST
              value: $(redis.REDIS_HOST)
            - name: REDIS_PORT
              value: $(redis.REDIS_PORT)
            - name: KAFKA_BROKER_LIST
              value: $(kafka.KAFKA_BROKER_LIST)
      restartPolicy: Never
  backoffLimit: 4
