apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: xw
spec:
  ports:
    - port: 2181
      name: zookeeper-port
      targetPort: 2181
  selector:
    app: zookeeper
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
  namespace: xw
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      nodePort: 30092
  selector:
    app: kafka
