apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: xw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "10.247.244.92:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://10.247.28.21:9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_BROKER_ID
              value: "1"

