apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: xw
  labels:
    app: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          imagePullPolicy: Always
          image: redis
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_AUTH
              valueFrom:
                configMapKeyRef:
                  key: redis.REDIS_AUTH
                  name: my-configmap
          command:
            - redis-server
            - --appendonly yes
            - --requirepass
          args:
            - "$(REDIS_AUTH)"
