apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: xw
  labels:
    app: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: xw
  labels:
    app: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: go-anything-service
  namespace: xw
  labels:
    app: go-anything-service
spec:
  selector:
    app: go-anything
  ports:
    - port: 38889
      targetPort: 8888
      protocol: TCP
  type: NodePort
